return {
  ensure_installed = {
      "vim",
      "vimdoc",
      "lua",
      "html",
      "css",
      "go",
      "rust",
      "typescript",
      "javascript",
      "jsdoc",
      "json",
      "jq",
      "svelte",
      "vue",
      "astro",
      "bash",
      "c",
      "c_sharp",
      "cpp",
      "cuda",
      "cmake",
      "clojure",
      "python",
      "perl",
      "pug",
      "templ",
      "ruby",
      "dart",
      "scala",
      "swift",
      "java",
      "elixir",
      "eex",
      "groovy",
      "glsl",
      "graphql",
      "gitignore",
      "nginx",
      "ninja",
      "make",
      "prisma",
      "proto",
      "sql",
      "terraform",
      "dockerfile",
  },

  -- When a file without parser been opened, auto install the parser
  auto_install = true,

  highlight = {
    enable = true,
  },

  indent = {
    enable = true,
  },
}
